@extends('layouts.backend_master')

@section('admin_contents')

<div class="card mb-4">
    <div class="card-header py-3 bg-light d-flex justify-content-between align-items-center">
        <div>
            <h5 class="mb-0 text-primary fw-bold">
                <i class="fas fa-history me-2"></i> All Generated Invoices Archive
            </h5>
            <small class="text-muted">Centralized repository of all invoices generated for students</small>
        </div>
        <a href="{{ route('admin.students.enrolled') }}" class="btn btn-primary btn-sm rounded-pill px-3">
            <i class="fas fa-plus me-1"></i> Generate New Invoice
        </a>
    </div>

    <div class="card-body">

        <form method="GET" action="{{ route('admin.invoices.history') }}" class="row g-2 mb-4">
            <div class="col-md-8">
                <div class="input-group">
                    <span class="input-group-text bg-white"><i class="fas fa-search text-muted"></i></span>
                    <input type="text" name="search" class="form-control" placeholder="Search by student name, code, email, or invoice title..." value="{{ request('search') }}">
                </div>
            </div>
            <div class="col-md-4 d-flex gap-2">
                <button type="submit" class="btn btn-secondary w-100"><i class="fas fa-filter me-1"></i> Filter Archive</button>
                @if(request('search'))
                    <a href="{{ route('admin.invoices.history') }}" class="btn btn-outline-danger" title="Reset Search"><i class="fas fa-redo"></i></a>
                @endif
            </div>
        </form>

        <div class="table-responsive">
            <table class="table table-hover table-striped align-middle border">
                <thead class="table-dark">
                    <tr>
                        <th style="width: 50px;">#</th>
                        <th>Student Name & Code</th>
                        <th>Invoice Title</th>
                        <th>Format</th>
                        <th>Generated By</th>
                        <th>Sent Status</th>
                        <th>Generated Date</th>
                        <th class="text-end" style="width: 180px;">Actions</th>
                    </tr>
                </thead>
                <tbody>
                    @forelse($invoices as $index => $item)
                        <tr>
                            <td>{{ $invoices->firstItem() + $index }}</td>
                            <td>
                                @if($item->student)
                                    <a href="{{ route('admin.students.show', $item->student->id) }}" class="fw-bold text-decoration-none">
                                        {{ $item->student->first_name }} {{ $item->student->surname }}
                                    </a>
                                    <div class="text-muted small">ID: {{ $item->student->student_id ?? ('STU-' . str_pad($item->student->id, 5, '0', STR_PAD_LEFT)) }}</div>
                                @else
                                    <span class="text-muted">Student Removed</span>
                                @endif
                            </td>
                            <td><strong>{{ $item->invoice_title }}</strong></td>
                            <td>
                                <span class="badge {{ $item->file_type === 'pdf' ? 'bg-danger' : 'bg-primary' }} text-uppercase">
                                    <i class="fas {{ $item->file_type === 'pdf' ? 'fa-file-pdf' : 'fa-file-word' }} me-1"></i> {{ $item->file_type }}
                                </span>
                            </td>
                            <td>{{ $item->generator->name ?? 'System Admin' }}</td>
                            <td>
                                @if($item->sent_to_student)
                                    <span class="badge bg-success" title="Sent: {{ $item->sent_at?->format('d M, Y h:i A') }}">Sent</span>
                                @else
                                    <span class="badge bg-secondary">Draft</span>
                                @endif
                            </td>
                            <td>{{ $item->created_at ? $item->created_at->format('d M, Y h:i A') : 'N/A' }}</td>
                            <td class="text-end">
                                @if(!$item->sent_to_student)
                                    <form action="{{ route('admin.students.invoices.send', $item->id) }}" method="POST" class="d-inline">
                                        @csrf
                                        @method('PATCH')
                                        <button type="submit" class="btn btn-sm btn-info text-white me-1" title="Send to Student Profile">
                                            <i class="fas fa-paper-plane"></i> Send
                                        </button>
                                    </form>
                                @endif
                                <a href="{{ route('admin.students.invoices.download', $item->id) }}" class="btn btn-sm btn-success me-1" title="Download File">
                                    <i class="fas fa-download"></i>
                                </a>
                                <form action="{{ route('admin.students.invoices.delete', $item->id) }}" method="POST" class="d-inline" onsubmit="return confirm('Are you sure you want to delete this generated invoice record?');">
                                    @csrf
                                    @method('DELETE')
                                    <button type="submit" class="btn btn-sm btn-danger" title="Delete Record">
                                        <i class="fas fa-trash-alt"></i>
                                    </button>
                                </form>
                            </td>
                        </tr>
                    @empty
                        <tr>
                            <td colspan="8" class="text-center py-4 text-muted">
                                <i class="fas fa-history fa-2x mb-2 d-block text-secondary"></i>
                                No generated invoice records found.
                            </td>
                        </tr>
                    @endforelse
                </tbody>
            </table>
        </div>

        <div class="d-flex justify-content-end mt-3">
            {{ $invoices->appends(request()->query())->links() }}
        </div>
    </div>
</div>

@endsection
