<?php $__env->startSection('admin_contents'); ?>

<div class="card mb-4">
    <div class="card-header py-3 bg-light d-flex justify-content-between align-items-center">
        <div>
            <h5 class="mb-0 text-primary fw-bold">
                <i class="fas fa-history me-2"></i> All Generated Invoices Archive
            </h5>
            <small class="text-muted">Centralized repository of all invoices generated for students</small>
        </div>
        <a href="<?php echo e(route('admin.students.enrolled')); ?>" class="btn btn-primary btn-sm rounded-pill px-3">
            <i class="fas fa-plus me-1"></i> Generate New Invoice
        </a>
    </div>

    <div class="card-body">

        <form method="GET" action="<?php echo e(route('admin.invoices.history')); ?>" class="row g-2 mb-4">
            <div class="col-md-8">
                <div class="input-group">
                    <span class="input-group-text bg-white"><i class="fas fa-search text-muted"></i></span>
                    <input type="text" name="search" class="form-control" placeholder="Search by student name, code, email, or invoice title..." value="<?php echo e(request('search')); ?>">
                </div>
            </div>
            <div class="col-md-4 d-flex gap-2">
                <button type="submit" class="btn btn-secondary w-100"><i class="fas fa-filter me-1"></i> Filter Archive</button>
                <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if(request('search')): ?>
                    <a href="<?php echo e(route('admin.invoices.history')); ?>" class="btn btn-outline-danger" title="Reset Search"><i class="fas fa-redo"></i></a>
                <?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
            </div>
        </form>

        <div class="table-responsive">
            <table class="table table-hover table-striped align-middle border">
                <thead class="table-dark">
                    <tr>
                        <th style="width: 50px;">#</th>
                        <th>Student Name & Code</th>
                        <th>Invoice Title</th>
                        <th>Format</th>
                        <th>Generated By</th>
                        <th>Sent Status</th>
                        <th>Generated Date</th>
                        <th class="text-end" style="width: 180px;">Actions</th>
                    </tr>
                </thead>
                <tbody>
                    <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::openLoop(); ?><?php endif; ?><?php $__empty_1 = true; $__currentLoopData = $invoices; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $index => $item): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::startLoopIteration(); ?><?php endif; ?>
                        <tr>
                            <td><?php echo e($invoices->firstItem() + $index); ?></td>
                            <td>
                                <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($item->student): ?>
                                    <a href="<?php echo e(route('admin.students.show', $item->student->id)); ?>" class="fw-bold text-decoration-none">
                                        <?php echo e($item->student->first_name); ?> <?php echo e($item->student->surname); ?>

                                    </a>
                                    <div class="text-muted small">ID: <?php echo e($item->student->student_id ?? ('STU-' . str_pad($item->student->id, 5, '0', STR_PAD_LEFT))); ?></div>
                                <?php else: ?>
                                    <span class="text-muted">Student Removed</span>
                                <?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
                            </td>
                            <td><strong><?php echo e($item->invoice_title); ?></strong></td>
                            <td>
                                <span class="badge <?php echo e($item->file_type === 'pdf' ? 'bg-danger' : 'bg-primary'); ?> text-uppercase">
                                    <i class="fas <?php echo e($item->file_type === 'pdf' ? 'fa-file-pdf' : 'fa-file-word'); ?> me-1"></i> <?php echo e($item->file_type); ?>

                                </span>
                            </td>
                            <td><?php echo e($item->generator->name ?? 'System Admin'); ?></td>
                            <td>
                                <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($item->sent_to_student): ?>
                                    <span class="badge bg-success" title="Sent: <?php echo e($item->sent_at?->format('d M, Y h:i A')); ?>">Sent</span>
                                <?php else: ?>
                                    <span class="badge bg-secondary">Draft</span>
                                <?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
                            </td>
                            <td><?php echo e($item->created_at ? $item->created_at->format('d M, Y h:i A') : 'N/A'); ?></td>
                            <td class="text-end">
                                <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if(!$item->sent_to_student): ?>
                                    <form action="<?php echo e(route('admin.students.invoices.send', $item->id)); ?>" method="POST" class="d-inline">
                                        <?php echo csrf_field(); ?>
                                        <?php echo method_field('PATCH'); ?>
                                        <button type="submit" class="btn btn-sm btn-info text-white me-1" title="Send to Student Profile">
                                            <i class="fas fa-paper-plane"></i> Send
                                        </button>
                                    </form>
                                <?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
                                <a href="<?php echo e(route('admin.students.invoices.download', $item->id)); ?>" class="btn btn-sm btn-success me-1" title="Download File">
                                    <i class="fas fa-download"></i>
                                </a>
                                <form action="<?php echo e(route('admin.students.invoices.delete', $item->id)); ?>" method="POST" class="d-inline" onsubmit="return confirm('Are you sure you want to delete this generated invoice record?');">
                                    <?php echo csrf_field(); ?>
                                    <?php echo method_field('DELETE'); ?>
                                    <button type="submit" class="btn btn-sm btn-danger" title="Delete Record">
                                        <i class="fas fa-trash-alt"></i>
                                    </button>
                                </form>
                            </td>
                        </tr>
                    <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::endLoop(); ?><?php endif; ?><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::closeLoop(); ?><?php endif; ?>
                        <tr>
                            <td colspan="8" class="text-center py-4 text-muted">
                                <i class="fas fa-history fa-2x mb-2 d-block text-secondary"></i>
                                No generated invoice records found.
                            </td>
                        </tr>
                    <?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
                </tbody>
            </table>
        </div>

        <div class="d-flex justify-content-end mt-3">
            <?php echo e($invoices->appends(request()->query())->links()); ?>

        </div>
    </div>
</div>

<?php $__env->stopSection(); ?>

<?php echo $__env->make('layouts.backend_master', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php /**PATH C:\laragon\www\iLap\resources\views\backend\invoice_templates\history.blade.php ENDPATH**/ ?>